name: build, test & publish Docker image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-test-publish:
    name: build, test & publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v4

    # docker/metadata-action currently ignores labels defined in the Dockerfile.
    # see https://github.com/docker/metadata-action/issues/295#issuecomment-2470700067
    - name: compute Docker image OCI metadata from commit & repo
      id: docker-metadata
      uses: docker/metadata-action@v5
      with:
        labels: |
          org.opencontainers.image.version=${{ github.event_name == 'push' && github.ref_type == 'tag' && github.ref_name }}

    - name: log into the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v3

    - name: build Docker image
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}
        context: .
        tags: |
          ghcr.io/${{ github.repository_owner }}/build123d:latest
        labels: ${{ steps.docker-metadata.outputs.labels }}
        annotations: ${{ steps.docker-metadata.outputs.annotations }}
        # todo: linux/arm64 (requires support by the cadquery-ocp package)
        platforms: linux/amd64
        # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
